### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by edofic** [ocharles/Francium#3]
I very new to GHCJS and its ecosystem and am very interested in Francium. However I cannot figure out  how to build it. `cabal install --ghcjs` fails and complains it doesn't know how to install `virtual-dom`. I see there is some configuration for nix but I have no idea how to use it.
Some documentation on how to build Francium (and hack on it!) would be very appreciated.

**Comment by ocharles** [comment]
Perfectly valid issue! Francium was built when GHCJS packaging in Nix was in a state of change, but that's mostly stabilised now. It will stil lbe a bit rocky as GHCJS is a bit of a moving target, but I'll see what i can do.

**Comment by purefn** [comment]
What nixpkgs repo and revision are you using to build francium? I can't get virtual-dom to compile, I keep running into https://github.com/NixOS/nixpkgs/issues/7768

**Comment by jkozlowski** [comment]
I managed to manually compile on GHC 7.10 following instructions on the ghcjs github page (although I will admit it was a weekend job), then compiled virtual-dom into a sandbox and then Francium into the same sandbox and so far so good. Now I am going to see if I can fix the todo-mvc...

**Comment by ocharles** [comment]
I am using 60f250e0da03afd53503490afe4af902b842a00a - which I think comes from https://github.com/ryantrinkle/nixpkgs/tree/ghcjs-ng

**Comment by arianvp** [comment]
I'm not very sure how Nix works. I got it installed now on my ArchLinux install but how do I use it to build this project?

**Comment by purefn** [comment]
@arianvp Here's what I've done.  I have a project that I want to use Francium in, so in that project I create a `default.nix`

```
{ mkDerivation, aeson, base, bytestring, francium, ghcjs-base
, ghcjs-dom, lens, mtl, stdenv, template-haskell, text
, transformers
}:
mkDerivation {
  pname = "naggy-ui";
  version = "0.1";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [
    aeson base bytestring francium ghcjs-base ghcjs-dom lens mtl
    template-haskell text transformers
  ];
  description = "UI for Naggy";
  license = stdenv.lib.licenses.unfree;
}
```

You can use cabal2nix to generate this from a cabal file if you run 

```
$ nix-env -i cabal2nix
$ cabal2nix . > default.nix
```

Then, you need to checkout Francium and virtual-dom

```
$ git clone https://github.com/ocharles/virtual-dom
$ git clone https://github.com/ocharles/Francium
```

Next, create a `shell.nix` file

```
with (import <nixpkgs> {}).pkgs;
with (import <nixpkgs/pkgs/development/haskell-modules/lib.nix> { inherit pkgs; });

let
  ghcjs-pkgs = haskell-ng.packages.ghcjs.override {
    overrides = self: super: {
      virtual-dom = self.callPackage ./virtual-dom {};
      francium = self.callPackage ./Francium {};
      naggy-ui= self.callPackage ./. {};
    };
  };
in
  (overrideCabal ghcjs-pkgs.naggy-ui (drv: {
    buildTools = [
      haskell-ng.packages.ghc7101.cabal-install
      nodejs
      nodePackages.uglify-js
    ];
  })).env
```

Now, you can use `nix-shell` to enter into an environment with cabal, ghcjs and all the dependencies your project needs.  Now you can run `cabal configure --ghcjs` and work on your project. If you need to add a dependency, add it to your `myproject.cabal` file, rerun `cabal2nix . > default.nix` and start a new nix shell.

**Comment by ocharles** [comment]
@purefn Is exactly correct, this is how I do it too. That said, this should reach the readme at some point. I will leave this open as a reminder, as it's only worth doing that work once Francium stabalises.

**Comment by ocharles** [comment]
Francium work has stopped and it's unclear when it will resume in the future. Closing this for now.
