### ISSUE TITLE
Update todo-mvc

### ISSUE THREAD

**Issue by purefn** [ocharles/Francium#5]
Since the update to virtual-dom, the todo-mvc example no longer builds.

**Comment by ocharles** [comment]
Indeed, there have been big changes to Francium too. I'll try and find some time to bring it all up to date.

**Comment by purefn** [comment]
One of the parts that has me most tripped up is the using the `state` behavior in the `ToDoItem` `render` function. Before it worked fine because `render` had the type `behavior HTML`, so you could just use applicative functor syntax. Now, `render` has the type `HTML behavior`, but when trying to `fmap` over `state` you end up with `Behavior t (HTML (Behavior t))`, and I can't figure out a way do anything with that. Any tips to get me going?

**Comment by ocharles** [comment]
Indeed, that is quite a big change - but ultimately it leads to code that's easier to write where the stuff that changes is "deep inside" a HTML structure. Previously you had to `fmap` repeatedly to get to where you want.

Now `HTML` itself can change without the need to fmap at all. However, what you have to do is use `embed :: Behavior t (HTML Identity) -> HTML (Behavior t)` to embed reactive HTML into a document. There is a converse `observe :: HTML (Behavior t) -> Behavior t (HTML Identity)` if you need to break some HTML apart.

**Comment by purefn** [comment]
Right, I found that what I needed was something akin to `embed (choose <$>
state <*> observeHTML renderList <*> observeHTML renderForm)`. Thanks.

**Comment by ocharles** [comment]
Yep, that looks about right! If you're finding it verbose or awkward though, feel free to throw some code at me. I have considered making HTML a full `Applicative` instance rather than just a monoid, and that may be helpful here - I'm not sure

**Comment by jkozlowski** [comment]
I am also having a go at fixing the todo-mvc examples for my own learning. I was wondering if there's a trick to drop the mconcat in the following code:

```
p_ (style .= lineHeight (1 :: Size Abs))
     (mconcat [ "Template by ",  "Bla bla" ])
```

In other words, the pre-refactor virtual-dom had a nice story about adding a list of children from a list, now I need to mconcat it.

**Comment by ocharles** [comment]
I'm starting to look into this again, as I experiment with rewriting Francium in terms of `frpnow`

**Comment by ocharles** [comment]
It's worth noting the current API is now:

``` haskell
p (style_ (lineHeight 1))
  (do "Template by "
      "Bla bla")
```

which hopefully removes the annoying need to call `mconcat` (though there are times when you'll have to `sequence`, but these occur less frequently).

**Comment by ocharles** [comment]
Francium work has stopped and it's unclear when it will resume.
