### ISSUE TITLE
Ajax

### ISSUE THREAD

**Issue by jkozlowski** [ocharles/Francium#6]
I have been playing with writing an Ajax module modelled on how baconjs does it(https://baconjs.github.io/tutorials.html). It would take an Event of requests and returns an event (or behaviour I haven't decided yet) of responses. Do you think this could be a useful addition?

The only thing that I am not sure about is whether it should use the raw XMLHttpRequest as your XHRIO module, or as I currently have it, jquery.

**Comment by ocharles** [comment]
Just wanted to update that I'm somewhat undecided on this, though mostly in favour of it. I can only really work on this stuff when Francium itself reaches stability, which we're still a bit off (waiting for GHCJS/reactive-banana to reach the necessary versions).

**Comment by ocharles** [comment]
I'm going to have to close this as I'm not currently working on `Francium`, and it's unclear what the future is. Sorry!
